spring.application.name=url-shortener
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/url_shortener}
server.port=${PORT:8080}
logging.level.root=INFO

app.base-url=${APP_BASE_URL:http://localhost:${server.port}}
app.analytics.recent-click-limit=20
